services:
  prismo-db:
    image: timescale/timescaledb:2.27.2-pg18
    container_name: prismo-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=prismo_admin
      - POSTGRES_PASSWORD=PrismoPasword123@
      - POSTGRES_DB=prismo_managemnet
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: